// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDCXs0mWk4-RdfrcBZjGi7-TtNhhO7tPI',
    appId: '1:404506820642:web:cb30c63b4a1cb3decc4a7b',
    messagingSenderId: '404506820642',
    projectId: 'sariscan',
    authDomain: 'sariscan.firebaseapp.com',
    storageBucket: 'sariscan.firebasestorage.app',
    measurementId: 'G-6SZ3TGLRLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbJuHMJdLsrlj90HTfPA_GDTg-Kf5ttgI',
    appId: '1:404506820642:android:4a07501395bb0cf1cc4a7b',
    messagingSenderId: '404506820642',
    projectId: 'sariscan',
    storageBucket: 'sariscan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnr7_8dk0phrNJ9Cyt7bQKzBiNGz4bXMI',
    appId: '1:404506820642:ios:80a14cd52d4342c8cc4a7b',
    messagingSenderId: '404506820642',
    projectId: 'sariscan',
    storageBucket: 'sariscan.firebasestorage.app',
    iosBundleId: 'com.example.sariScanApp',
  );
}
