-- SariScan schema for the existing Supabase tables.
-- Keeps supplied bigint keys and normalized relations, adds Auth ownership and
-- stable app IDs. Legacy rows stay intact and unassigned instead of being
-- silently attached to the wrong shop.

create table if not exists public.users (
  user_id bigint generated by default as identity primary key,
  username varchar(255) not null unique,
  password_hash varchar(255),
  full_name varchar(60) not null,
  role varchar(20) not null default 'owner',
  auth_user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
create table if not exists public.categories (
  category_id bigint generated by default as identity primary key,
  category_name varchar(50) not null,
  description varchar(150),
  user_id bigint references public.users(user_id) on delete cascade
);
create table if not exists public.customers (
  customer_id bigint generated by default as identity primary key,
  full_name varchar(60) not null,
  contact_number varchar(20),
  created_at timestamptz not null default now(),
  user_id bigint references public.users(user_id) on delete cascade,
  app_id varchar(20)
);
create table if not exists public.products (
  product_id bigint generated by default as identity primary key,
  product_name varchar(60) not null,
  barcode varchar(30),
  category_id bigint references public.categories(category_id)
    on update cascade on delete set null,
  unit_price numeric(10, 2) not null default 0 check (unit_price >= 0),
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  low_stock_threshold integer not null default 0
    check (low_stock_threshold >= 0),
  created_at timestamptz not null default now(),
  user_id bigint references public.users(user_id) on delete cascade,
  app_id varchar(20),
  is_archived boolean not null default false
);
create table if not exists public.transactions (
  transaction_id bigint generated by default as identity primary key,
  receipt_number varchar(20) not null,
  user_id bigint not null references public.users(user_id)
    on update cascade on delete restrict,
  customer_id bigint references public.customers(customer_id)
    on update cascade on delete set null,
  transaction_date timestamptz not null default now(),
  total_amount numeric(10, 2) not null default 0 check (total_amount >= 0),
  amount_received numeric(10, 2) not null default 0
    check (amount_received >= 0),
  change_amount numeric(10, 2) not null default 0
    check (change_amount >= 0),
  payment_type varchar(10) not null,
  status varchar(15) not null default 'completed'
);
create table if not exists public.transaction_items (
  transaction_item_id bigint generated by default as identity primary key,
  transaction_id bigint not null references public.transactions(transaction_id)
    on update cascade on delete cascade,
  product_id bigint not null references public.products(product_id)
    on update cascade on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10, 2) not null check (unit_price >= 0),
  subtotal numeric(10, 2) not null check (subtotal >= 0)
);
create table if not exists public.utang_ledger (
  ledger_id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(customer_id)
    on update cascade on delete restrict,
  transaction_id bigint references public.transactions(transaction_id)
    on update cascade on delete set null,
  entry_type varchar(10) not null,
  amount numeric(10, 2) not null check (amount >= 0),
  balance_after numeric(10, 2) not null,
  entry_date timestamptz not null default now(),
  app_id varchar(20),
  note varchar(150) not null default ''
);

-- Upgrade tables already created from the supplied SQL.
alter table public.users add column if not exists auth_user_id uuid;
alter table public.users alter column password_hash drop not null;
alter table public.users alter column username type varchar(255);
alter table public.users alter column role set default 'owner';
alter table public.categories add column if not exists user_id bigint;
alter table public.customers add column if not exists user_id bigint;
alter table public.customers add column if not exists app_id varchar(20);
alter table public.products add column if not exists user_id bigint;
alter table public.products add column if not exists app_id varchar(20);
alter table public.products add column if not exists is_archived boolean
  not null default false;
alter table public.utang_ledger add column if not exists app_id varchar(20);
alter table public.utang_ledger add column if not exists note varchar(150)
  not null default '';

do $$
begin
  if not exists (select 1 from pg_constraint where conname =
      'users_auth_user_id_fkey' and conrelid = 'public.users'::regclass) then
    alter table public.users add constraint users_auth_user_id_fkey
      foreign key (auth_user_id) references auth.users(id) on delete cascade;
  end if;
  if not exists (select 1 from pg_constraint where conname =
      'categories_user_id_fkey' and conrelid = 'public.categories'::regclass) then
    alter table public.categories add constraint categories_user_id_fkey
      foreign key (user_id) references public.users(user_id) on delete cascade;
  end if;
  if not exists (select 1 from pg_constraint where conname =
      'customers_user_id_fkey' and conrelid = 'public.customers'::regclass) then
    alter table public.customers add constraint customers_user_id_fkey
      foreign key (user_id) references public.users(user_id) on delete cascade;
  end if;
  if not exists (select 1 from pg_constraint where conname =
      'products_user_id_fkey' and conrelid = 'public.products'::regclass) then
    alter table public.products add constraint products_user_id_fkey
      foreign key (user_id) references public.users(user_id) on delete cascade;
  end if;
end;
$$;

alter table public.categories drop constraint if exists categories_category_name_key;
alter table public.products drop constraint if exists products_barcode_key;
alter table public.transactions drop constraint if exists transactions_receipt_number_key;
create unique index if not exists users_auth_user_id_unique
  on public.users(auth_user_id);
create unique index if not exists categories_user_name_unique
  on public.categories(user_id, lower(category_name));
create unique index if not exists products_user_app_id_unique
  on public.products(user_id, app_id);
create unique index if not exists products_user_barcode_unique
  on public.products(user_id, barcode)
  where barcode is not null and barcode <> '' and is_archived = false;
create unique index if not exists customers_user_app_id_unique
  on public.customers(user_id, app_id);
create unique index if not exists transactions_user_receipt_unique
  on public.transactions(user_id, receipt_number);
create unique index if not exists ledger_customer_app_id_unique
  on public.utang_ledger(customer_id, app_id);
create index if not exists transactions_user_date_idx
  on public.transactions(user_id, transaction_date desc);
create index if not exists ledger_customer_date_idx
  on public.utang_ledger(customer_id, entry_date desc);

create or replace function public.ensure_sariscan_user()
returns bigint language plpgsql security definer set search_path = '' as $$
declare
  v_auth_user_id uuid := auth.uid();
  v_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  v_name text := coalesce(
    nullif(auth.jwt() -> 'user_metadata' ->> 'display_name', ''), 'Store Owner');
  v_user_id bigint;
begin
  if v_auth_user_id is null then raise exception 'Authentication is required'; end if;
  select user_id into v_user_id from public.users
    where auth_user_id = v_auth_user_id;
  if v_user_id is null and v_email <> '' then
    update public.users set auth_user_id = v_auth_user_id, full_name = v_name
      where lower(username) = v_email and auth_user_id is null
      returning user_id into v_user_id;
  end if;
  if v_user_id is null then
    insert into public.users
      (username, password_hash, full_name, role, auth_user_id)
    values (coalesce(nullif(v_email, ''), v_auth_user_id::text), null,
      v_name, 'owner', v_auth_user_id)
    returning user_id into v_user_id;
  end if;
  return v_user_id;
end;
$$;

create or replace function public.handle_new_sariscan_auth_user()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  v_username text := lower(coalesce(new.email, new.id::text));
  v_name text := coalesce(
    nullif(new.raw_user_meta_data ->> 'display_name', ''), 'Store Owner');
begin
  update public.users set auth_user_id = new.id, full_name = v_name
    where lower(username) = v_username and auth_user_id is null;
  if not found then
    insert into public.users
      (username, password_hash, full_name, role, auth_user_id)
    values (v_username, null, v_name, 'owner', new.id)
    on conflict (auth_user_id) do update set full_name = excluded.full_name;
  end if;
  return new;
end;
$$;
drop trigger if exists on_sariscan_user_created on auth.users;
create trigger on_sariscan_user_created after insert on auth.users
  for each row execute procedure public.handle_new_sariscan_auth_user();

create or replace function public.upsert_sariscan_product(
  p_app_id text, p_name text, p_category text, p_price numeric,
  p_stock integer, p_barcode text, p_low_stock_threshold integer,
  p_is_archived boolean
) returns void language plpgsql security definer set search_path = '' as $$
declare
  v_user_id bigint := public.ensure_sariscan_user();
  v_category_id bigint;
  v_category_name text := coalesce(nullif(trim(p_category), ''), 'General');
begin
  if nullif(trim(p_app_id), '') is null or nullif(trim(p_name), '') is null
      or p_price <= 0 or p_stock < 0 or p_low_stock_threshold < 0 then
    raise exception 'Invalid product data';
  end if;
  select category_id into v_category_id from public.categories
    where user_id = v_user_id and lower(category_name) = lower(v_category_name);
  if v_category_id is null then
    begin
      insert into public.categories (user_id, category_name)
        values (v_user_id, v_category_name)
        returning category_id into v_category_id;
    exception when unique_violation then
      select category_id into v_category_id from public.categories
        where user_id = v_user_id and lower(category_name) = lower(v_category_name);
    end;
  end if;
  insert into public.products
    (user_id, app_id, product_name, barcode, category_id, unit_price,
     stock_quantity, low_stock_threshold, is_archived)
  values (v_user_id, trim(p_app_id), trim(p_name), nullif(trim(p_barcode), ''),
    v_category_id, p_price, p_stock, p_low_stock_threshold, p_is_archived)
  on conflict (user_id, app_id) do update set
    product_name = excluded.product_name, barcode = excluded.barcode,
    category_id = excluded.category_id, unit_price = excluded.unit_price,
    stock_quantity = excluded.stock_quantity,
    low_stock_threshold = excluded.low_stock_threshold,
    is_archived = excluded.is_archived;
end;
$$;

create or replace function public.upsert_sariscan_customer(
  p_app_id text, p_name text, p_phone text
) returns void language plpgsql security definer set search_path = '' as $$
declare v_user_id bigint := public.ensure_sariscan_user();
begin
  if nullif(trim(p_app_id), '') is null or nullif(trim(p_name), '') is null then
    raise exception 'Invalid customer data';
  end if;
  insert into public.customers (user_id, app_id, full_name, contact_number)
  values (v_user_id, trim(p_app_id), trim(p_name), nullif(trim(p_phone), ''))
  on conflict (user_id, app_id) do update set
    full_name = excluded.full_name, contact_number = excluded.contact_number;
end;
$$;

create or replace function public.record_sariscan_payment(
  p_app_id text, p_customer_app_id text, p_amount numeric,
  p_entry_date timestamptz, p_note text
) returns void language plpgsql security definer set search_path = '' as $$
declare
  v_user_id bigint := public.ensure_sariscan_user();
  v_customer_id bigint;
  v_balance numeric(10, 2);
begin
  select customer_id into v_customer_id from public.customers
    where user_id = v_user_id and app_id = p_customer_app_id;
  if v_customer_id is null then
    raise exception 'Customer does not belong to the signed-in shop';
  end if;
  select coalesce(sum(case when entry_type = 'credit' then amount else -amount end), 0)
    into v_balance from public.utang_ledger where customer_id = v_customer_id;
  if p_amount <= 0 or p_amount > v_balance then
    raise exception 'Payment must be greater than zero and no more than the balance';
  end if;
  insert into public.utang_ledger
    (customer_id, transaction_id, entry_type, amount, balance_after,
     entry_date, app_id, note)
  values (v_customer_id, null, 'payment', p_amount, v_balance - p_amount,
    coalesce(p_entry_date, now()), p_app_id,
    coalesce(nullif(trim(p_note), ''), 'Customer payment'))
  on conflict (customer_id, app_id) do nothing;
end;
$$;

create or replace function public.save_sariscan_sale(
  p_sale jsonb, p_items jsonb, p_ledger jsonb default null
) returns void language plpgsql security definer set search_path = '' as $$
declare
  v_user_id bigint := public.ensure_sariscan_user();
  v_customer_id bigint;
  v_transaction_id bigint;
  v_product_id bigint;
  v_item jsonb;
  v_quantity integer;
  v_total numeric(10, 2) := (p_sale ->> 'total')::numeric;
  v_received numeric(10, 2) := (p_sale ->> 'amount_received')::numeric;
  v_change numeric(10, 2) := (p_sale ->> 'change_amount')::numeric;
  v_payment_type text := p_sale ->> 'payment_type';
  v_items_total numeric(10, 2) := 0;
  v_balance numeric(10, 2);
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'A sale must contain at least one item';
  end if;
  if v_total < 0 or v_payment_type not in ('cash', 'utang') then
    raise exception 'Invalid sale data';
  end if;
  if v_payment_type = 'cash'
      and (v_received < v_total or v_change <> v_received - v_total) then
    raise exception 'Cash totals do not balance';
  end if;
  if v_payment_type = 'utang' and (v_received <> 0 or v_change <> 0) then
    raise exception 'Utang sales cannot contain cash or change';
  end if;
  if nullif(p_sale ->> 'customer_id', '') is not null then
    select customer_id into v_customer_id from public.customers
      where user_id = v_user_id and app_id = p_sale ->> 'customer_id';
    if v_customer_id is null then
      raise exception 'Customer does not belong to the signed-in shop';
    end if;
  end if;
  if v_payment_type = 'utang' and v_customer_id is null then
    raise exception 'An utang sale requires a customer';
  end if;
  insert into public.transactions
    (receipt_number, user_id, customer_id, transaction_date, total_amount,
     amount_received, change_amount, payment_type, status)
  values (p_sale ->> 'id', v_user_id, v_customer_id,
    (p_sale ->> 'created_at')::timestamptz, v_total, v_received, v_change,
    v_payment_type, 'completed')
  on conflict (user_id, receipt_number) do nothing
  returning transaction_id into v_transaction_id;
  if v_transaction_id is null then return; end if;

  for v_item in select value from jsonb_array_elements(p_items) loop
    v_quantity := (v_item ->> 'quantity')::integer;
    if v_quantity <= 0 then
      raise exception 'Sale item quantity must be greater than zero';
    end if;
    select product_id into v_product_id from public.products
      where user_id = v_user_id and app_id = v_item ->> 'product_id'
        and not is_archived;
    if v_product_id is null then
      raise exception 'A sale product does not belong to the signed-in shop';
    end if;
    update public.products set stock_quantity = stock_quantity - v_quantity
      where product_id = v_product_id and stock_quantity >= v_quantity;
    if not found then
      raise exception 'Insufficient database stock for a sale item';
    end if;
    insert into public.transaction_items
      (transaction_id, product_id, quantity, unit_price, subtotal)
    values (v_transaction_id, v_product_id, v_quantity,
      (v_item ->> 'unit_price')::numeric,
      v_quantity * (v_item ->> 'unit_price')::numeric);
    v_items_total := v_items_total
      + v_quantity * (v_item ->> 'unit_price')::numeric;
  end loop;
  if v_items_total <> v_total then
    raise exception 'Sale header total does not match its items';
  end if;

  if v_payment_type = 'utang' then
    if p_ledger is null then raise exception 'An utang sale requires a ledger entry'; end if;
    select coalesce(sum(case when entry_type = 'credit' then amount else -amount end), 0)
      into v_balance from public.utang_ledger where customer_id = v_customer_id;
    insert into public.utang_ledger
      (customer_id, transaction_id, entry_type, amount, balance_after,
       entry_date, app_id, note)
    values (v_customer_id, v_transaction_id, 'credit', v_total,
      v_balance + v_total, (p_ledger ->> 'created_at')::timestamptz,
      p_ledger ->> 'id',
      coalesce(nullif(p_ledger ->> 'note', ''), 'Utang sale'));
  end if;
end;
$$;

alter table public.users enable row level security;
alter table public.categories enable row level security;
alter table public.customers enable row level security;
alter table public.products enable row level security;
alter table public.transactions enable row level security;
alter table public.transaction_items enable row level security;
alter table public.utang_ledger enable row level security;
revoke all on public.users from anon, authenticated;
revoke all on public.categories from anon, authenticated;
revoke all on public.customers from anon, authenticated;
revoke all on public.products from anon, authenticated;
revoke all on public.transactions from anon, authenticated;
revoke all on public.transaction_items from anon, authenticated;
revoke all on public.utang_ledger from anon, authenticated;
grant select on public.categories, public.customers, public.products,
  public.transactions, public.transaction_items, public.utang_ledger
  to authenticated;

drop policy if exists users_owner_access on public.users;
create policy users_owner_access on public.users for select to authenticated
  using (auth_user_id = (select auth.uid()));
drop policy if exists categories_owner_access on public.categories;
create policy categories_owner_access on public.categories for select to authenticated
  using (user_id = (select public.ensure_sariscan_user()));
drop policy if exists customers_owner_access on public.customers;
create policy customers_owner_access on public.customers for select to authenticated
  using (user_id = (select public.ensure_sariscan_user()));
drop policy if exists products_owner_access on public.products;
create policy products_owner_access on public.products for select to authenticated
  using (user_id = (select public.ensure_sariscan_user()));
drop policy if exists transactions_owner_access on public.transactions;
create policy transactions_owner_access on public.transactions for select to authenticated
  using (user_id = (select public.ensure_sariscan_user()));
drop policy if exists transaction_items_owner_access on public.transaction_items;
create policy transaction_items_owner_access on public.transaction_items
  for select to authenticated using (exists (
    select 1 from public.transactions transaction_owner
    where transaction_owner.transaction_id = transaction_items.transaction_id
      and transaction_owner.user_id = (select public.ensure_sariscan_user())));
drop policy if exists utang_ledger_owner_access on public.utang_ledger;
create policy utang_ledger_owner_access on public.utang_ledger
  for select to authenticated using (exists (
    select 1 from public.customers customer_owner
    where customer_owner.customer_id = utang_ledger.customer_id
      and customer_owner.user_id = (select public.ensure_sariscan_user())));

revoke execute on function public.ensure_sariscan_user() from public, anon;
revoke execute on function public.upsert_sariscan_product(
  text, text, text, numeric, integer, text, integer, boolean) from public, anon;
revoke execute on function public.upsert_sariscan_customer(
  text, text, text) from public, anon;
revoke execute on function public.record_sariscan_payment(
  text, text, numeric, timestamptz, text) from public, anon;
revoke execute on function public.save_sariscan_sale(
  jsonb, jsonb, jsonb) from public, anon;
grant execute on function public.ensure_sariscan_user() to authenticated;
grant execute on function public.upsert_sariscan_product(
  text, text, text, numeric, integer, text, integer, boolean) to authenticated;
grant execute on function public.upsert_sariscan_customer(
  text, text, text) to authenticated;
grant execute on function public.record_sariscan_payment(
  text, text, numeric, timestamptz, text) to authenticated;
grant execute on function public.save_sariscan_sale(
  jsonb, jsonb, jsonb) to authenticated;
